### ISSUE TITLE
Missing Attributions

### ISSUE THREAD

**Issue by DarcyManoel** [LinearPerk/Sci-Fi-Flavours#2]
While exploring the contents of this collection I noticed you're missing attributions for my content and many others. While you have posted acknowledgements for plugins (excluding mine :P), you should be mentioning each author you are using the content of while listing all their borrowed content (see base game Endless Sky for an example on proper copyright acknowledgment).

In regards to content of mine you haven't attributed- from [Adde Endless Sky](https://github.com/Adde-Endless-Sky/AES-Misc)
**Ships:**
- aesalon.png

**Outfits:**
- chain_blaster_turret.png
- dual_electron_beam.png
- flame_thrower.png
- ion_mortar.png
- knockout_gas.png
- quad_plasma_turret.png
- shipwright_gear.png
- single_bed.png
- smugglers_fittings.png
- storage_lockers.png
- tool_rack.png
- type_0_radiant_engine.png

**plasma_repeater.png** can also be removed from this collection because it has since been merged into the main game :D. You can reference it from base game files now and the attribution exists in the base game so just a heads up on that one.

I understand this is a relatively new collection and dealing with attributions/copyright can be a headache a lot of the time but it's important to ensure you're properly attributing the content creators you're borrowing content from.

**Comment by LinearPerk** [comment]
Hi Darcman99,

Please accept my apologies for the sloppy attribution. I have a new workflow for attribution and plan to resolve all of these issues on the next update.

Also thank you for the feedback. I've really enjoyed all of the content that you've created for endless sky! I am mortified that I overlooked you in the general acknowledgments. :(

 I agree that those general acknowledgments are insufficient. I'm currently mobile only but I expect to be able to resolve this issue as soon as I get back to home base.
